### ISSUE TITLE
Error after uploading the plugin

### ISSUE THREAD

**Issue by 7oda187** [PayTabsLLC/OpenCart-2.3.x-Credit-Card#1]
Hello Team,

There is an error after uploading the plugin files to the root of the script and trying to install the extinsion i got this error:
**Notice: Error: Could not load template C:/xampp/htdocs/test/admin/view/template//payment/paytabs.tpl! in C:\xampp\htdocs\test\system\storage\modification\system\library\template\php.php on line 23**

Can you please assist me to resolve this issue.

**Comment by Jakson2030** [comment]
Did you get this error from the zip file or from the files ?

**Comment by 7oda187** [comment]
After i download the file from here for the latest version i copied all the files to the root file for opencart when i try to install it i got this error message.

**Comment by 7oda187** [comment]
Any update on that issue?

**Comment by absamuth** [comment]
i faced this problem too!!

any update???

**Comment by Jakson2030** [comment]
Hi,

Try the attached file and let me know if are still facing the issue.

[Opencart2.3 2.zip](https://github.com/PayTabsLLC/OpenCart-2.3.x-Credit-Card/files/785611/Opencart2.3.2.zip)

**Comment by absamuth** [comment]
Hi,

works fine, but i got this WARNING at my checkout page " payment method "

**Warning: Invalid argument supplied for foreach() in public_html/vqmod/vqcache/vq2-system_engine_loader.php on line 53Notice: Undefined property: Proxy::getMethod in public_html/catalog/controller/quickcheckout/payment_method.php on line 110**

im using:
opencart 2.3
+ "quick checkout" extension

please help, ThankYouu

**Comment by 7oda187** [comment]
Dear Jamal, 

I have installed your file and got this error when i try to chose paytabs for payment: 
**Notice: Undefined index: terms in C:\xampp\htdocs\test\catalog\view\theme\default\template\checkout\payment_method.tpl on line 16**

**Comment by Jakson2030** [comment]
Hello @7oda187,

Try to replace the attached file in this directory and try again.
catalog\view\theme\default\template\checkout\payment_method.tpl
[Uploading payment_method.tpl.zip…]()

Regards,

**Comment by absamuth** [comment]
Dear @Jamalc0m

there's no payment_method.tpl file in your opencart 2.3 files !
could you give me this file?
because i've this problem
**Warning: Invalid argument supplied for foreach() in public_html/vqmod/vqcache/vq2-system_engine_loader.php on line 53Notice: Undefined property: Proxy::getMethod inpublic_html/catalog/controller/checkout/payment_method.php on line 53**

and your link up there is not working.

Thank You...

**Comment by 7oda187** [comment]
Dear @Jamalc0m 
I'm trying to download the file : " Uploading payment_method.tpl.zip…" but there is nothing there would you upload it again please that well be appreciated.

Regards,

**Comment by Jakson2030** [comment]
@7oda187,@absamuth, 
Get in touch at support@paytabs.com to check your issue.

**Comment by absamuth** [comment]
Dear @Jamalc0m 

i think you should install opencart 2.3
and try to upload paytabs plugin files
see all the errors, and resolve it

that's better
ThankYou...

**Comment by 7oda187** [comment]
Dear @Jamalc0m 

I'm already in contact with the support team, and they informed me to download this file: https://github.com/PayTabsLLC/OpenCart-2.3.x-Credit-Card/blob/master/Opencart2.3.zip
I  have the file already but there is an issue on it and i'm trying to resolve it with you.

So would you please assist us so we can resolve the issue together to make this plug-in work properly.

Regards,

**Comment by Jakson2030** [comment]
Dears,

Its working fine with Opencart 2.3, I can see all you have vqmod installed, can you try to uninstall it as this plugin modify opencart core which may it cause this issue.

I am using fresh Opencart without vqmod.

Regards,

**Comment by absamuth** [comment]
Dear @Jamalc0m 

 2.2 OC version works fine with vqmod
why not with opencart 2.3 ?
so you telling me there's no way it work without uninstalling vqmod?
im sorry but thats make me turn back to PayFort 
and lotta costumers will do.

Regards,,,

**Comment by Jakson2030** [comment]
Dear @absamuth,

Kindly update the attached zip file and remove the following file:
**catalog/model/payment/paytabs.php an try again**

[Opencart2.3.zip](https://github.com/PayTabsLLC/OpenCart-2.3.x-Credit-Card/files/801838/Opencart2.3.zip)

**Comment by absamuth** [comment]
Dear @Jamalc0m 

thank youuu

**Comment by 7oda187** [comment]
Dear @Jamalc0m 

Thank you so much for your assist.
